name: park_benching
description: A new Flutter project.

publish_to: 'none'

version: 1.0.1+2

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  flutter_rating_bar: ^4.0.0
  get: ^4.6.5
  get_storage: ^2.0.3
  firebase_auth: ^3.3.19
  firebase_storage:
  firebase_analytics:
  firebase_core: ^1.17.1
  firebase_app_check: ^0.0.6+13
  cloud_firestore: ^3.1.17

  google_maps_flutter: ^2.1.7
  geolocator: ^8.2.1
  geocoding: ^2.0.4
  image_picker: ^0.8.5+3
  fluttertoast: ^8.0.9
  geoflutterfire: ^3.0.3
  custom_radio_grouped_button:
  share_plus: ^4.0.7
  cached_network_image:
  custom_map_markers: ^0.0.2+1
  url_launcher: ^6.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/montserrat/Montserrat-Thin.ttf
          weight: 100
        - asset: assets/fonts/montserrat/Montserrat-Light.ttf
          weight: 300
        - asset: assets/fonts/montserrat/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/montserrat/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/montserrat/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/montserrat/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/montserrat/Montserrat-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/montserrat/Montserrat-Black.ttf
          weight: 900


    - family: Mulish
      fonts:
        - asset: assets/fonts/mulish/Mulish-Regular.ttf
          weight: 400
        - asset: assets/fonts/mulish/Mulish-Medium.ttf
          weight: 500
        - asset: assets/fonts/mulish/Mulish-SemiBold.ttf
          weight: 600

